### ISSUE TITLE
Error: Calling needs :cxx11 is disabled! There is no replacement.

### ISSUE THREAD

**Issue by Maxador** [eXolnet/homebrew-deprecated#2]
Please report this to the exolnet/deprecated tap:
  /usr/local/Homebrew/Library/Taps/exolnet/homebrew-deprecated/Formula/php@7.0.rb:45

**Comment by wawagit** [comment]
idem for php@5.6.rb

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/exolnet/homebrew-deprecated/Formula/php@5.6.rb

Calling needs :cxx11 is disabled! There is no replacement.

Please report this to the exolnet/deprecated tap:
  /usr/local/Homebrew/Library/Taps/exolnet/homebrew-deprecated/Formula/php@5.6.rb:44

**Comment by clns** [comment]
Any solution to this?

**Comment by pgrenaud** [comment]
Hi!

Thanks for reporting this. Its seems like homebrew decided to deprecate a dependency requirement. 😅 Fortunately, the fix was pretty easy. I've already pushed the required modifications. No need to rebuild the bottles. Just run `brew update` and you should be good to go! 👌 

Have a nice day!

PS: I leave this here for reference.

* https://github.com/Homebrew/homebrew-core/commit/b3d5eb8dda7bbcddf3c7998d066aa99cfba3450e
* https://github.com/Homebrew/homebrew-core/commit/b2b4a493e59e8babf0567b3b64619219c27578ba
* https://github.com/Homebrew/homebrew-core/commit/ffba9990ffd9bb747ab82bbbb83bc191f35c02e2
